FROM ruby:<%= class_options[:ruby_version] %>

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update -qq && apt-get install -y build-essential

# # for postgres
# RUN apt-get install -y libpq-dev

# # for nokogiri
# RUN apt-get install -y libxml2-dev libxslt1-dev

# # for capybara-webkit
# RUN apt-get install -y libqtwebkit4 libqt4-dev xvfb

# for a JS runtime
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get install -y nodejs

RUN node -v
RUN npm -v

RUN npm install yarn -g

ENV APP_HOME /<%= application_name %>
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME

RUN yarn install --check-files

EXPOSE 3000

ENTRYPOINT bin/rails server --port 3000 -b 0.0.0.0