FROM ruby:<%= class_options[:ruby_version] %>

RUN apt-get update -qq && apt-get install -y npm build-essential cron
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs
RUN npm install yarn -g

ENV APP_HOME /<%= application_name %>
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN bundle install
RUN yarn install --check-files

ADD . $APP_HOME

RUN RAILS_ENV=production rails assets:precompile
RUN service cron start

EXPOSE 3000

ENTRYPOINT rake db:migrate && bin/rails server --port 3000 -b 0.0.0.0